= 冲突
:nofooter:

冲突一定会发生，越亲密的人，在一块的时间越长，肯定就会发生冲突，不可避免

== 冲突的性质

=== 冲突的定义

当个体的动机、目标、信念、观点或行为妨碍别人，或者与别人矛盾，就会发生 *人际冲突*

=== 冲突的频率

* 儿童与母亲：每3.6min一次
* 青少年：每天7次
* 情侣：每周2.3次
* 中年夫妻：每月1-2次

以上皆为统计数据

=== 导致冲突的因素

* 人格
* 依恋类型
* 生命阶段
* 相似性
* 酒精

== 冲突的过程

=== 激发事件

* 批评
* 无理要求
* 拒绝
* 积累的烦恼

=== 归因

* 善意vs恶意
* 内部vs外部

=== 介入和升级

* 介入
** 协商
** 升级
* 避免

=== 接近/退避模式

=== 协商和顺应

.四种应对冲突的类型
|===
|- |主动 |被动

|*建设性*
|讨论
|忠诚

|*破坏性*
|离开
|忽视
|===

=== 应对冲突：四类夫妻

* 多变型
* 确认型
* 逃避型
* 敌对型

== 冲突的结果

=== 冲突的结束

* 分离
* 支配
* 妥协
* 整合一致
* 结构性改善

=== 冲突的益处

*听话者-说话者技术*

当讨论变得激烈，是否想保持冷静？请遵循以下规则：

==== 双方的规则

一、说话者拥有发言权，利用真实的小物件，比如一本书或者电视遥控器作为发言权的标志，任何人拥有了发言权，就是唯一能说话的人，直到他说完为止

二、分享发言权，如果你是说话者，不要没完没了说个不停，每次轮到你说话时，请保持简洁，当发言权易手时请同时转换角色

三、不要解决问题，该技术的要点是描述分歧，而不是解决它，共同进行头脑风暴可以解决这一问题

==== 说话者的规则

四、独自说话，不要试图猜测别人的心思，请使用第一人称陈述来描述你自己的想法、感情和关心的问题，不要谈论你对伴侣动机或观点的看法

五、停顿，并让听话者复述你刚刚说过的话语，如果他不十分准确，请礼貌地重申任何混淆之处，目标是帮助听话者，真正的理解你

==== 听话者的规则

六、复述你听到的话语，用你自己的语言重新说出你听到的内容，以此向说话者证明你在仔细倾听，关键是确保你理解了对方所想表达的意思

七、集中关注说话者的信息，不要反驳，除非你拥有了发言权，否则不要提出你对议题的想法和观点，作为听话者，你的任务只能是为了理解你的伴侣而说话
