= 我读《拉伸——最好的运动》
:nofooter:

== 概述

长久缺乏运动会导致肌肉紧绷缩短，失去弹性，拉伸可以使肌肉保持弹性，为运动做好准备，运动前后的拉伸回降低运动损伤的可能性

根据自己的肌肉灵活度，紧张度柔韧度做个性化的练习

拉伸的目的是降低肌肉的紧张度，保持灵活性

运动要循序渐进，从易到难，不要为难自己，要逐渐增大强度

== 谁应当拉伸

只要身体健康，没有特殊疾病，就可以拉伸，如果近期生过病或者做过手术，需要咨询专业人士之后再进行拉伸

== 何时拉伸

随时随地

== 有何益处

* 缓解肌肉紧张，放松身体
* 有助于更加轻松自如的活动，提高身体协调性
* 有助于扩大身体的活动范围
* 有助于预防肌肉扭伤等运动损伤
* 为高强度运动做好准备，使运动更容易
* 有助于保持身体柔韧度，使身体不会因为年龄的增大而变得僵硬
* 有助于提高对自己身体的了解。在你拉伸时，你会讲注意力集中在这些部位，并与他们进行交流
* 有助于放松大脑对身体的控制，使身体“为运动而运动”，而不是为竞争或者虚荣而运动
* 让你感觉更好

== 如何拉伸

几个原则

* 放松的
* 持续的
* 注意力集中的

*下面一段话至关重要，是全书的精华部分*

开始一个拉伸动作时，先进行10-15秒的轻松拉伸，动作要慢，但感觉到有轻微的拉伸张力时，保持这个动作，同时注意放松。在这一过程中，拉伸感会慢慢消失，如果没有消失，那么稍微放松身体，达到一个令你感到舒适的拉伸。轻松拉伸能缓解肌肉的僵硬和紧张，为进阶拉伸做好准备

进阶拉伸就是轻松拉伸动作的重复，轻松拉伸之后，继续移动自己的身体，感觉到有轻微的拉伸张力时，保持这个动作，同时注意放松，保持10-15秒。在这一过程中，拉伸感会慢慢消失，如果没有消失，那么稍微放松身体，达到一个令你感到舒适的拉伸感

> 如果在保持某个动作的时候，感觉到拉伸感增加了，或者感到了疼痛，那么就是拉伸过度了

在拉伸过程中，呼吸应该是平顺的，不要屏息，在身体前屈的时候呼气，其他时候正常的呼吸

可以在拉伸某一个部位时，心中默默计数，确保拉伸的时间足够长，在熟练之后，凭着感觉就可以了

> *牵张反射* 是一种肌肉的自我保护机制，在肌纤维过度拉伸时，神经就会发射信号是肌肉收缩，防止肌肉受到损伤。因此，过度拉伸会导致本要放松的肌肉变得更紧张

=== 好的拉伸是什么样的

通过轻松拉伸和进阶拉伸之后，你的身体柔韧性应该会自然而然的增加，经过持续的有规律的拉伸，你的柔韧性会越来越好，逐渐突破自己的极限

=== 热身活动

低强度运动一会，预热一下肌肉和软组织即可

=== 整理运动

在运动过后，先平复到运动之前的水平之后再进行拉伸，防止肌肉酸痛和僵硬

=== 跟着感觉拉伸

拉伸要跟着感觉走，不要试图挑战自己的极限

全书的理论内容到此为止，后面是大量的实践和练习，运动没有捷径，跟着做吧