= 原则的重要性
:nofooter:

I believe that having principles that work is essential for getting what we want out of life. I also believe that to understand each other we have to understand each other’s principles. That is why I believe we need to talk about them.

We will begin by examining the following questions:

* What are principles?
* Why are principles important?
* Where do principles come from?
* Do you have principles that you live your life by? What are they?
* How well do you think they will work, and why?

Answer all questions with complete honesty, without worrying what I or others might think. That honesty will allow you to be comfortable living with your own principles, and to judge yourself by how consistently you operate by them. If you don’t have many well-thought-out principles, don’t worry. We will get there together, if we remain open-minded.

1) What are principles?

----
Your values are what you consider important, literally what you “value.” Principles are what allow you to live a life consistent with those values. Principles connect your values to your actions; they are beacons that guide your actions, and help you successfully deal with the laws of reality. It is to your principles that you turn when you face hard choices.
----

2) Why are principles important?

----
All successful people operate by principles that help them be successful. Without principles, you would be forced to react to circumstances that come at you without considering what you value most and how to make choices to get what you want. This would prevent you from making the most of your life. While operating without principles is bad for individuals, it is even worse for groups of individuals (such as companies) because it leads to people randomly bumping into each other without understanding their own values and how to behave in order to be consistent with those values.
----

3) Where do principles come from?

----
Sometimes we forge our own principles and sometimes we accept others’ principles, or holistic packages of principles, such as religion and legal systems. While it isn’t necessarily a bad thing to use others’ principles—it’s difficult to come up with your own, and often much wisdom has gone into those already created—adopting pre-packaged principles without much thought exposes you to the risk of inconsistency with your true values. Holding incompatible principles can lead to conflict between values and actions—like the hypocrite who has claims to be of a religion yet behaves counter to its teachings. Your principles need to reflect values you really believe in.

4) Do you have principles that you live your life by? What are they?

----
Your principles will determine your standards of behavior. When you enter into relationships with other people, your and their principles will determine how you interact. People who have shared values and principles get along. People who don’t will suffer through constant misunderstandings and conflicts with one another. Too often in relationships, people’s principles are unclear. Think about the people with whom you are closest. Are their values aligned with yours?
----

.What do you value most deeply?
****
jjk
****

5) How well do you think they will work, and why?

Those principles that are most valuable come from our own experiences and our reflections on those

experiences. Every time we face hard choices, we refine our principles by asking ourselves difficult

questions. For example, when our representatives in Washington are investigating whether various

segments of society are behaving ethically, they are simultaneously grappling with questions such as,

“Should the government punish people for bad ethics, or should it just write and enforce the laws?”

Questions of this kind—in this case, about the nature of government—prompt thoughtful assessments

of alternative approaches. These assessments in turn lead to principles that can be applied to similar

occasions in the future. As another example, “I won’t steal” can be a principle to which you refer

when the choice of whether or not to steal arises. But to be most effective, each principle must be

consistent with your values, and this consistency demands that you ask: Why? Is the reason you

won’t steal because you feel empathy for your potential victim? Is it because you fear getting caught?

By asking such questions, we refine our understanding, and the development of our principles

becomes better aligned with our core values. To be successful, you must make correct, tough choices.

You must be able to “cut off a leg to save a life,” both on an individual level and, if you lead people, on

a group level. And to be a great leader, it is important to remember that you will have to make these

choices by understanding and caring for your people, not by following them.

You have to answer these questions for yourself. What I hope for most is that you will carefully consider the

principles we will be exploring in this document and try operating by them as part of the process of discovering

what works best for you. In time, the answers to these questions will evolve from “Ray’s principles” to “my

principles,” and “Ray” will fade from the picture in much the same way as memories of your ski instructor or

basketball coach fade after you have mastered the sport.

So, as I believe that adopting pre-packaged principles without much thought is risky, I am asking you to join me

in thoughtfully discussing the principles that guide how we act. When considering each principle, please ask

yourself, “Is it true?” While this particular document will always express just what I believe, other people will

certainly have their own principles, and possibly even their own principles documents, and future managers of

Bridgewater will work in their own ways to determine what principles Bridgewater will operate by. At most, this

will remain as one reference of principles for people to consider when they are deciding what’s important and

how to behave.
