= 原则的重要性
:nofooter:

Principles are concepts that can be applied over and over again in similar circumstances as distinct from narrow answers to specific questions.

Every game has principles that successful players master to achieve winning results.

So does life. Principles are ways of successfully dealing with the laws of nature or the laws of life. Those who understand more of them and understand them well know how to interact with the world more effectively than those who know fewer of them or know them less well.

Different principles apply to different aspects of life e.g.,there are “skiing principles” for skiing, “parenting principles” for parenting, “management principles” for managing, “investment principles” for investing, etc. and there are over-arching “life principles” that influence our approaches to all things. And, of course, different people subscribe to different principles that they believe work best.

I am confident that whatever success Bridgewater and I have had has resulted from our operating by certain principles.

Creating a great culture, finding the right people, managing them to do great things, and solving problems creatively and systematically are challenges faced by all organizations.

What differentiates them is how they approach these challenges. The principles laid out in the pages that follow convey our unique ways of doing these things, which are the reasons for our unique results.

Bridgewater’s success has resulted from talented people operating by the principles set out here, and it will continue if these or other talented people continue to operate by them. Like getting fit, virtually anyone can do it if they are willing to do what it takes.

What is written here is just my understanding of what it takes: my most fundamental life principles, my approach to getting what I want, and my “management principles,” which are based on those foundations.

Taken together, these principles are meant to paint a picture of a process for the systematic pursuit of truth and excellence and for the rewards that accompany this pursuit. I put them in writing for people to consider in order to help Bridgewater and the people I care about most.

Until recently, I didn’t write out these principles because I felt that it was presumptuous for me to tell others what would work best for them.

But over time, I saw the people who I cared about most struggling with problems and wanted to help them; I also found that their problems were almost always the result of violating one or more of these principles, and that their problems could be solved by applying these principles.

So I began writing down the types of problems and the broken principles that caused them.

When I began, I didn’t know how many principles I would end up with but, through this process, I discovered that about 200 principles pretty much cover all the problems. I’m sure that I will come up with more as I learn more.

When I say that these are my principles, I don’t mean that in a possessive or egotistical way.I just mean that they are explanations of what I personally believe. I believe that the people I work with and care about must think for themselves.

I set these principles out and explained the logic behind them so that we can together explore their merits and stress test them.

While I am confident that these principles work well because I have thought hard about them, they have worked well for me for many years, and they have stood up to the scrutiny of the hundreds of smart, skeptical people, I also believe that nothing is certain. I believe that the best we can hope for is highly probable.By putting them out there and stress testing them, the probabilities of their being right will increase.

I also believe that those principles that are most valuable to each of us come from our own encounters with reality and our reflections on these encounters—not from being taught and simply accepting someone else’s principles.

So, I put these out there for you to reflect on when you are encountering your realities, and not for you to blindly follow. What I hope for most is that you and others will carefully consider them and try operating by them as part of your process for discovering what works best for you.

Through this exploration, and with their increased usage, not only will they be understood, but they will evolve from “Ray’s principles” to “our principles,” and Ray will fade out of the picture in much the same way as memories of one’s ski or tennis instructor fade and people only pay attention to what works.

2 So, when digesting each principle, please…

 > …ask yourself: “Is it true?”

Before I discuss the management principles themselves, it’s important for me to articulate my own most fundamental life principles because my management principles are an extension of them.

In Part 1, I explain what I mean by principles, why I believe they are important, and how they are essential for getting what you want out of life.

Part 2 explains my most fundamental life principles. I describe what I believe are the best ways of interacting with reality to learn what it’s like, and how to most effectively deal with it to get what you want.

I also discuss what I believe are the most common traps that people fall into that prevent them from getting what they want, and how people’s lives can be radically better by avoiding them.

I wrote this so you can better understand why my other principles are what they are, though you don’t need to read this part to understand the others.

Part 3 is about my management principles. As I have run Bridgewater for more than 35 years, it explains Bridgewater’s approach up till now.

It begins at the big-picture, conceptual level, with an explanation of why I believe that any company’s results are primarily determined by its people and its culture. 

It then drills down into what I believe are the important principles behind creating a great culture: hiring the right people, managing them to achieve excellence, solving problems systematically, and making good decisions.

There are of course lots of other types of principles. For example, I hope to one day write about my investment principles. However, management principles are now what we need most, so here are the ones that I think make sense and have worked for me.
